import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ��ереклади для всієї платформи
const translations = {
  ru: {
    // Bottom Navigation
    'nav.wallet': 'Портфель',
    'nav.market': 'Ринок',
    'nav.bonuses': 'Бонусы',
    'nav.history': 'История',
    
    // Settings
    'settings.title': 'ОСНОВНЫЕ НАСТРОЙКИ',
    'settings.notifications': 'Уведомления',
    'settings.passcode': 'Код-па��оль и Face ID',
    'settings.language': 'Язык',
    'settings.currency': 'Основная валюта',
    'settings.enabled': 'Вкл',
    'settings.verification': 'Уровень в��рификации',
    'settings.max': 'Макси',
    'settings.not_applies': 'Не распространяется на аккаунт CFD Space.',
    'settings.support': 'Обратиться в поддержку',
    'settings.faq': 'FAQ Коше��ька',
    'settings.news': 'Новости Кошелька',
    'settings.agreement': 'Пользовательское соглашение',
    'settings.privacy': 'Политика конфиденциальности',
    'settings.footer_text': 'Мини-приложение управляется TG Wallet Inc.',
    'settings.footer_text2': 'Сервис независим и не ��вя��ан с Telegram.',
    'settings.learn_more': 'Узнать больше',
    'settings.basicSettingsTitle': 'ОСНОВНЫЕ НАСТРОЙКИ',
    'settings.walletTab': 'Портфель',
    'settings.cfdSpaceTab': 'CFD',
    'settings.verificationLevel': 'Уровень верификации',
    'settings.maxiVerification': 'Макси',
    'settings.contactSupport': 'Обратиться в поддержку',
    'settings.walletFAQ': 'FAQ Портфеля',
    'settings.walletNews': 'Новости Портфеля',
    'settings.cfdNotApplicable': 'Распространяется на аккаунт CFD',
    'settings.userAgreement': 'Пользовательское соглашение',
    'settings.privacyPolicy': 'Политика конфиденциальности',
    'settings.managedBy': 'Мини-приложение управляется TG Portfolio Inc.',
    'settings.independent': 'Сервис независим и не связан с Telegram.',
    'settings.learnMore': 'Узнать больше',
    
    // Language Selection
    'language.title': 'ЯЗЫК',
    'language.english': 'English',
    'language.russian': 'Русский',
    
    // Notifications
    'notifications.title': 'УВЕДОМЛЕНИЯ',
    'notifications.market_trends': 'Тренды рынка',
    'notifications.market_trends_desc': 'Изменение цен на активы',
    'notifications.updates': 'Обновления',
    'notifications.updates_desc': 'Новые сервисы и возможности',
    'notifications.promotions': 'Акции',
    'notifications.promotions_desc': 'Розыгрыши и бонусы',
    'notifications.educational': 'Об��азовательный ко��тент',
    'notifications.educational_desc': 'Гайды и советы',
    'notifications.feedback': 'Обратная связ��',
    'notifications.feedback_desc': 'Опросы и исследования',
    'notifications.always_on': 'Уведомлен��я о транзакциях и безопасности всегда будут включен��.',
    'notifications.news_channel': 'Все новости вы можете прочитать в канале',
    'notifications.crypto_news': 'Новости Крипто Кошелька',
    'notifications.cfd_title': 'УВЕДОМЛЕНИЯ CFD КОШЕЛЬКА',
    'notifications.cfd_for': 'Уведомления для',
    'notifications.cfd_desc': 'Получайте уве��омления, когда вам приходят CFD токены и NFT в CFD К��шелёк.',
    'notifications.cfd_news': 'Новости CFD Кошелька',
    'notifications.cfd_news_text': 'Все новости можно узнать в канале',
    'notifications.on': 'Вкл',
    'notifications.off': 'Выкл',
    'notifications.enabled': 'Вкл',
    'notifications.disabled': 'Выкл',
    'notifications.security_notice': 'Уведомления о транзакциях и безопасности всегда будут включены.',
    'notifications.news_text': 'Все новости вы можете прочитать в канале',
    'notifications.news_channel_link': 'Новости Крипто Кошелька',
    'notifications.cfd_title': 'УВЕДОМЛЕНИЯ CFD КОШЕЛЬКА',
    'notifications.cfd_for': 'Уведомления для',
    'notifications.cfd_description': 'Получайте уведомления, когда вам приходят CFD токены и NFT в CFD Кошелёк.',
    'notifications.cfd_news_text': 'Все новости можно узнать в канал��',
    'notifications.cfd_news_channel_link': 'Новости CFD Кошелька',
    
    // Notification Categories
    'notifications.category.market_trends': 'УВЕДОМЛЕНИЯ ТРЕНДОВ РЫНКА',
    'notifications.category.updates': 'У������ОМЛЕНИЯ ОБНОВЛЕНИЙ',
    'notifications.category.promotions': 'УВЕДОМЛЕНИЯ АКЦИЙ',
    'notifications.category.educational': 'УВЕДОМЛЕНИЯ ОБРАЗОВАТЕЛЬНОГО КОНТЕНТА',
    'notifications.category.feedback': 'УВЕДОМЛЕНИЯ ОБ ОБРАТНОЙ СВЯЗИ',
    'notifications.category.feedback_desc': 'Опросы пользователей, ��оторые помогают улучши��ь сервис.',
    
    // Wallet
    'wallet.title': 'Портфель',
    'wallet.balance.portfolio': 'Баланс Портфеля',
    'wallet.balance.allTime': 'за весь час',
    'wallet.actions.withdraw': 'Вывести',
    'wallet.actions.deposit': 'Пополнить',
    'wallet.actions.exchange': 'Обменять',
    'wallet.actions.transfer': 'Перевести',
    'wallet.notification.earnTitle': 'Зарабатывайте до 15% APY',
    'wallet.notification.withDollars': 'с Nobel Portfolio',
    'wallet.notification.startEarning': 'Начать зарабатывать →',
    'wallet.assets.title': 'АКТИВЫ',
    'wallet.assets.hide': 'Скрыть',
    'wallet.assets.show': 'Показать',
    'wallet.assets.cashDollars': 'Долл��ры',
    'wallet.assets.forTrading': 'Для тор��овли',
    'wallet.assets.boughtAt': 'Купил�� за:',
    'wallet.assets.noAssets': 'Пока нет активо��',
    'wallet.assets.buyOnMarket': 'Купи��е активы на странице Рынок',
    'wallet.trending.title': 'В ТРЕНДЕ',
    'wallet.trending.viewAll': 'Все',
    'wallet.trending.perDay': 'за день',
    'wallet.demo.message': '🎭 Demo режим - для полных ф��нкций запустите через Telegram бота',
    'wallet.tabs.wallet': 'Портфель',
    'wallet.tabs.cfd': 'CFD',
    'wallet.settings.open': 'Открыть настройки',
    'wallet.trading.title': 'Торговля',
    'wallet.trading.currentPrice': 'Текущая цена',
    'wallet.trading.buy': 'КУПИТЬ',
    'wallet.trading.sell': 'ПРОДАТЬ',
    'wallet.trading.warning': 'Торговля криптовалютами связана с высокими рисками',
    'wallet.gold': 'Золото',

    // Додаткові переклади для всіх текстів
    'wallet.notification.earnTitle': 'Зарабатывайте до 15% APY',
    'wallet.notification.withDollars': 'с Nobel Portfolio',
    'wallet.notification.startEarning': 'Начать зарабатывать →',
    'wallet.trending.perDay': 'за день',
    'wallet.demo.message': '🎭 Demo режим - для полных функций запустите через Telegram бота',
    'wallet.settings.open': 'Открыть настройки',
    
    // Market
    'market.title': 'Ринок',
    'market.search_placeholder': 'Поиск',
    'market.trending_title': 'В ТРЕНДЕ',
    'market.per_day': 'за день',
    'market.top_of_day': 'ТОП ДНЯ',
    'market.tab.all': 'Все',
    'market.tab.stocks': 'Акции',
    'market.tab.crypto': 'Криптовалюты',
    'market.tab.gold': 'Золото',
    'market.asset.gold': 'Золото',
    'market.asset.silver': 'Серебро',
    'market.asset.platinum': 'Платина',

    // History Page - базов�� переклади
    'history.transaction.buy': 'Покупка',
    'history.transaction.sell': 'Продаж',
    'history.operations_history': 'История операций',
    'history.time.just_now': 'Только что',
    'history.no_transactions': 'Пока не�� транзакций',
    'history.go_to_trading': 'Перейти к торговле',

    // Bonuses Page
    'bonuses.title_header': 'Бонусы в Кошельке',
    'bonuses.subtitle': 'Получ��йте бонусы за хранение криптовалюты.',
    'bonuses.how_it_works': 'Как это работает',
    'bonuses.tab.active': 'Активные',
    'bonuses.tab.completed': 'Завер��ённые',

    // CoinDetail Page
    'coin.about.crypto': 'О КРИПТОВАЛЮТЕ',
    'coin.about.stock': 'ОБ АКЦИИ',
    'coin.about.precious_metal': 'О ДРАГОЦЕННОМ МЕТАЛЛЕ',
    'coin.about.currency': 'О ВАЛЮТЕ',
    'coin.in_portfolio': 'В ПОРТФЕЛЕ',
    'coin.balance': 'Баланс',
    'coin.quantity': 'Количество',
    'coin.current_value': 'Текущая стоимость',
    'coin.btn.buy': 'Купить',
    'coin.btn.sell': 'Продать',
    'coin.btn.deposit': 'Пополнить',
    'coin.btn.withdraw': 'Вывести',

    // Exchange Page
    'exchange.title_header': 'Обмен',
    'exchange.you_pay': 'Вы платите',
    'exchange.you_receive': 'Вы получаете',
    'exchange.max': 'Макс',
    'exchange.search': 'Поиск',
    'exchange.back': '��азад',
    'exchange.asset.dollars': 'Доллары',

    // Додаткові переклади для завершення Wallet.tsx
    'wallet.trending.viewAll': 'Все',
    'wallet.trending.title': 'В ТРЕНДЕ',
    'wallet.demo.message': '🎭 Demo режим - для полных функций запустите через Telegram бота',
    'wallet.settings.open': 'Открыть настройки',
    'wallet.user.avatar': 'аватар пользователя',
    'wallet.assets.boughtFor': 'Купили за',
    'wallet.trends.perDay': 'за день',
    'wallet.assets.dollars_cash': 'Доллары USD',
    'wallet.assets.for_trading': 'для инвестирования',
    'wallet.assets.no_assets': 'Пока нет активов',
    'wallet.assets.buy_on_market': 'Купите активы на странице Рынок',

    // Deposit Pages
    'deposit.method.title': 'Как вы хотите купить',
    'deposit.method.subtitle': 'крипт��валюту',
    'deposit.method.bank_card': 'Банковская карта',
    'deposit.method.bank_card_desc': 'Купить криптовалюту ��о кар��е',
    'deposit.method.p2p_express': 'P2P Экспресс',
    'deposit.method.p2p_express_desc': 'Сделк�� с надёжными продавцами',
    'deposit.method.p2p_market': 'P2P Маркет',
    'deposit.method.p2p_market_desc': 'Купить без посре��ников',
    'deposit.method.telegram_stars': 'Пополнить через Telegram Stars',
    'deposit.method.external_wallet': 'Внешний кошелёк',
    'deposit.method.external_wallet_desc': 'Перевести с другого кошел��ка',

    // Deposit Asset Selection
    'deposit.asset.popular': 'ПОПУЛЯРНЫЕ',
    'deposit.asset.all': 'ВСЕ',
    'deposit.asset.not_found': 'Активы не найдены',

    // Deposit Network Selection
    'deposit.network.warning': 'Убедитесь, что вы выбрали нужную сеть. Неверный выбор может привест�� к утрате средств.',
    'deposit.network.select': 'ВЫБЕРИТЕ СЕТЬ',

    // Deposit Address
    'deposit.address.title': 'Ваш адрес в',
    'deposit.address.warning_start': 'На этот адрес отправляйте только',
    'deposit.address.warning_end': 'Активы других сетей или NFT будут безвозврат��о утрачены.',
    'deposit.address.qr_description': 'Отсканируйте QR-код для отправки',
    'deposit.address.qr_description_end': 'на свой кошелёк.',
    'deposit.address.your_address': 'Ваш адрес',
    'deposit.address.copy': 'Копировать адре��',
    'deposit.address.copied': 'Адрес скопирован в буфер',
    'deposit.address.copied_notification': 'Адрес скопирован в буфер.',

    // Withdraw Pages
    'withdraw.method.title': 'Как отправить',
    'withdraw.method.subtitle': 'криптовалюту',
    'withdraw.method.telegram.title': 'Контакт в Telegram',
    'withdraw.method.telegram.description': 'Мгновенно и без комиссий',
    'withdraw.method.external.title': 'Внешний кошелёк или б��ржа',
    'withdraw.method.external.description': '��ужно указать криптоадрес',

    // Withdraw Asset Selection
    'withdraw.asset.title': 'ВЫ ВЫВОДИТЕ',
    'withdraw.asset.dollars': 'Доллары',

    // Withdraw Amount
    'withdraw.amount.insufficient_funds': 'Недостаточно средств.',
    'withdraw.amount.buy_more': 'До��упить.',
    'withdraw.amount.balance': 'Баланс',
    'withdraw.amount.max': 'Макс.',
    'withdraw.amount.next': 'Далее',

    // Withdraw Processing
    'withdraw.processing.exchange_completed': 'Обмен выпол��ен!',
    'withdraw.processing.payment_processing': 'Ва�� платёж в обработке',
    'withdraw.processing.exchange_success': 'Вы успешно обменяли {amount} USD на {starsAmount} Telegram Stars',
    'withdraw.processing.stars_available': 'Stars уже доступны в вашем аккаунте Telegram',
    'withdraw.processing.time_estimate': 'Это займет от 5 до 20 минут',
    'withdraw.processing.notification_promise': 'Мы уведомим вас, когда транзакция будет п��дтверждена',
    'withdraw.processing.amount': 'Сумма',
    'withdraw.processing.received': 'Получено',
    'withdraw.processing.recipient': '��олучатель',
    'withdraw.processing.network': 'Сеть',
    'withdraw.processing.status': 'Статус',
    'withdraw.processing.return_to_portfolio': 'Вернуться к портфелю',
    'withdraw.processing.telegram_stars_exchange': 'Обмен на Telegram Stars',
    'withdraw.processing.external_withdrawal': 'Вывод на внешний кошелёк',

    // CFD Page
    'cfd.title': 'CFD Торговля',
    'cfd.balance.title': 'Баланс CFD',
    'cfd.balance.description': 'Средства для контрактов на разность цен',
    'cfd.trading_balance': 'Торговый ба��анс CFD',
    'cfd.search_assets': 'Поиск активов',
    'cfd.popular_pairs': 'ПОПУЛЯРНЫЕ ПАРЫ',
    'cfd.buy': 'КУПИТЬ',
    'cfd.sell': 'ПРОДАТЬ',
    'cfd.nav.market': 'Рынок',
    'cfd.nav.trades': 'Сделки',
    'cfd.nav.autotrading': 'Автоторговля',
    'cfd.nav.history': 'История',

    // Asset Detail Page
    'asset.name.dollars': 'Доллары',
    'asset.name.toncoin': 'Toncoin',
    'asset.name.bitcoin': 'Bitcoin',
    'asset.name.ethereum': 'Ethereum',
    'asset.name.gold': 'Золото',
    'asset.header.wallet_verified': 'Гаманець ✓',
    'asset.header.mini_app': 'мініЗастосунок',
    'asset.action.send': 'Отправить',
    'asset.action.receive': 'Получить',
    'asset.action.buy': 'Купить',
    'asset.action.exchange': 'Обменять',
    'asset.price.title': 'ЦЕНА',
    'asset.price.details': 'Подробнее',
    'asset.price.24h': '24ч',
    'asset.transaction_history': 'ИСТОРИЯ ТРАНЗАКЦИЙ',
    'asset.transaction.exchange_btc_usdt': 'Обмен: BTC на USDT',
    'asset.transaction.exchange_ton_btc': 'Обмен: TON на BTC',
    'asset.transaction.status.sent': 'Отправлено',
    'asset.transaction.status.received': 'Получено',
    'asset.transaction.date.dec_6': '6 дек. 2024 г. в 1...',
    'asset.transaction.date.nov_16': '16 нояб. 2024 г...',
    'asset.not_found': 'Актив не найден',
    
    // History
    'history.title': 'История',
    'history.all': 'Все',
    'history.deposits': 'Пополнения',
    'history.withdrawals': 'Выводы',
    'history.trades': 'Сделки',
    'history.transfers': 'Переводы',
    'history.no_transactions': 'У вас ��ока нет транзакций',
    'history.start_trading': 'Начните торговать, чтобы ув��деть историю здесь',

    // Additional History translations
    'history.subtitle': 'Все ваши транзакции и операции',
    'history.filter.all': 'Все',
    'history.filter.buy': 'Покупки',
    'history.filter.sell': 'Продажи',
    'history.filter.deposit': 'Пополнения',
    'history.filter.withdraw': 'Выведения',
    'history.empty.title': 'Пока нет транзак��ий',
    'history.empty.subtitle_all': 'Ваши операции появятся здесь',
    'history.empty.subtitle_filtered': 'Нет операций этого типа',
    'history.empty.go_to_market': 'Перейти к торговле',
    'history.transaction.buy': 'Покупка',
    'history.transaction.sell': 'Продажа',
    'history.transaction.asset': 'акти��а',
    'history.transaction.deposit': 'Пополнение звездами',
    'history.transaction.withdraw': 'Выведение в звезды',
    'history.transaction.transfer_to_cfd': 'Пере��од в CFD',
    'history.transaction.transfer_from_cfd': 'Перевод из CFD',
    'history.transaction.default': 'Транзакция',
    'history.time.now': 'То��ько что',
    'history.time.hours_ago': 'ч назад',
    'history.time.days_ago': 'д�� назад',
    'history.portfolio.total_value': 'Общая стоимость портфеля',
    'history.portfolio.cash': 'Наличные',
    'history.status.completed': 'Завершено',
    'history.status.pending': 'Ожидание',
    'history.status.processing': 'В обработке',
    'history.status.failed': 'Неуспешно',

    // History Details Modal
    'history.details.title': 'Детали транзакции',
    'history.details.group.label': 'Тип операции',
    'history.details.group.purchase': 'Покупка',
    'history.details.group.sale': 'Продажа',
    'history.details.group.deposit': 'Пополнение',
    'history.details.group.withdrawal': 'Выведение',
    'history.details.group.transfer': 'Перевод',
    'history.details.group.other': 'Другое',
    'history.details.id': 'Номер транзакции',
    'history.details.amount': 'Сумма',
    'history.details.instrument': 'Инструмент',
    'history.details.exchange_rate': 'Курс обмена',
    'history.details.purchase_price': 'Цена покупки',
    'history.details.quantity': 'Количество',
    'history.details.time': 'Время',
    'history.details.status': 'Статус',
    'history.details.description': 'Описание',
    
    // Bonuses
    'bonuses.title': 'Бонусы',
    'bonuses.hero.title': 'Бону��ы в Кошельке',
    'bonuses.hero.subtitle': '��олучайте бонусы за хранение криптовалюты.',
    'bonuses.hero.how_it_works': 'Как это работает',
    'bonuses.tabs.active': 'Активные',
    'bonuses.tabs.completed': 'Завершённые',
    'bonuses.card.bonus_label': 'БОНУС',
    'bonuses.card.annual': 'годо��ых',
    'bonuses.empty.completed': 'Нет завершённых бонусов',
    'bonuses.asset.dollars': 'Доллары',

    // Exchange
    'exchange.title': 'Обмен',
    'exchange.you_pay': 'Вы платите',
    'exchange.you_receive': 'Вы получаете',
    'exchange.max': 'Макс',
    'exchange.asset.dollars': 'Доллары',
    'exchange.top_up': 'Пополнить',
    'exchange.insufficient_funds': 'Недостаточно средств.',
    'exchange.select_instrument': 'Выбрать инструмент',
    'exchange.exchanging': 'Обмениваем...',
    'exchange.review_deal': 'Просмотреть сделку',
    'exchange.error.exchange_failed': 'Ошибка при обмене активов',

    // Transfer
    'transfer.title': 'Перевод сре��ств',
    'transfer.subtitle': 'Между Портфелем и CFD',
    'transfer.portfolio': 'Портфель',
    'transfer.cash': 'Наличные',
    'transfer.for_trading': 'Для торговли',
    'transfer.direction.to_cfd': 'Перевод в CFD',
    'transfer.direction.from_cfd': 'Перевод из CFD',
    'transfer.amount_label': 'Сумма перево��а',
    'transfer.all_amount': 'Вся сумма',
    'transfer.available': 'Доступно',
    'transfer.amount': 'Сумма',
    'transfer.from': 'Из',
    'transfer.to': 'В',
    'transfer.fee': 'Комиссия',
    'transfer.transferring': 'Пер��водим...',
    'transfer.transfer_button': 'Перевести',
    'transfer.info.title': 'О перевод��',
    'transfer.info.portfolio_desc': 'Портфель - ��аличные для покупки активов',
    'transfer.info.cfd_desc': 'CFD - средства для контрактов ��а разность цен',
    'transfer.info.instant_free': 'Перевод мгновенный без ��омиссии',
    'transfer.info.history_saved': 'Все операции сохраняются в истории',
    'transfer.error.invalid_amount': 'Некорректная сумма',
    'transfer.error.insufficient_funds': 'Недостаточно средств',
    'transfer.error.transfer_failed': 'Ошибка перевода',
    
    // Asset Details
    'asset.about': 'О КРИПТОВАЛЮТЕ',
    'asset.about_stock': 'ОБ АКЦИИ',
    'asset.about_gold': 'О ЗОЛОТЕ',
    'asset.about_currency': 'О ВАЛЮТЕ',
    'asset.portfolio': 'В портфеле',
    'asset.not_in_portfolio': 'Нет активов в по��тфеле',
    'asset.transaction_history': 'История операций',
    'asset.no_transactions': 'Нет операций с ��тим активом',
    'asset.buy': 'Купить',
    'asset.sell': 'Продать',
    'asset.deposit_btn': 'Пополнить',
    'asset.withdraw_btn': 'Вывести',

    // CoinDetail Page
    'coin.about_crypto': 'О КРИПТОВАЛЮТЕ',
    'coin.about_stock': 'ПРО АКЦИЮ',
    'coin.about_precious_metal': 'ПРО ДОРОГОЦІННИЙ МЕТАЛ',
    'coin.about_currency': 'ПРО ВАЛЮТУ',
    'coin.portfolio_section': 'У ПОРТФЕЛІ',
    'coin.read_more': 'Докладніше',
    'coin.portfolio_empty': 'Немає активів в портфелі',
    'coin.time_period.1d': '1Д',
    'coin.time_period.7d': '7Д',
    'coin.time_period.1m': '1М',
    'coin.time_period.1y': '1Г',
    'coin.time_period.all': 'Все',
    'coin.today': 'Сегодня',
    'coin.btc_description': 'Bitcoin — це перша і найвідоміша криптовалюта у світі. Створена в 2009 році Сатоші Накамото як децентралізована цифрова валюта.',
    'coin.btc_point_1': 'Ви можете купувати, продавати або зберігати BTC в Гаманці.',
    'coin.btc_point_2': 'Bitcoin використовує технологію блокчейн для забе��печення безпеки та прозорості.',
    'coin.eth_description': 'Ethereum — це платформа для розумних контрактів і децентралізова��их додатк��в (DApps), запущена в 2015 році.',
    'coin.eth_point_1': 'Ви можете купувати, продавати або зберігати ETH в Гаманці.',
    'coin.eth_point_2': 'Ethereum є основою для багатьох DeFi проектів та NFT.',
    'coin.aapl_description': 'Apple Inc. — американська багатонаціональна технологічна корпорація, відома своїми продуктами iPhone, iPad, Mac та іншими пристроями.',
    'coin.xrp_description': 'XRP — це цифрова валюта, створена компанією Ripple для миттєвих міжнародних переказів та платежів.',
    'coin.xrp_point_1': 'Ви можете купувати, ��родавати або зберігати XRP в Гаманці.',
    'coin.xrp_point_2': 'XRP використовується банками та фінансовими установами для швидких переказів.',
    'coin.generic_crypto_description': '{{name}} — це криптовалюта на базі блокчейн технології. Дозволяє здійснювати швидкі та безпечні цифрові транзакції.',
    'coin.generic_crypto_point_1': 'Ви можете купувати, продавати або зберігати {{symbol}} в Гама��ці.',
    'coin.generic_crypto_point_2': 'Криптовалюти можуть мати високу волатильність цін.',
    'coin.gold_description': 'Золото — це дорогоцінний метал, який протягом тисячоліть використовується як засіб збереження вартості та захисту від інфляції.',
    'coin.gold_point_1': 'Ви можете купувати або продавати золото через платформу.',
    'coin.gold_point_2': 'Золото традиційно вважається "безпечним притулком" для інвесторів.',

    // Exchange
    'exchange.title': 'Обмен',
    'exchange.you_pay': 'Вы платите',
    'exchange.you_receive': 'Вы получаете',
    'exchange.rate': 'Курс',
    'exchange.min_amount': 'Мин. сумма',
    'exchange.max_amount': 'Макс. сумма',
    'exchange.exchange_btn': 'Обменять',
    'exchange.insufficient_balance': 'Недостаточно средств',
    'exchange.max': 'Макс',
    'exchange.processing': 'Обминяем...',
    'exchange.review_deal': 'Переглянути угоду',
    'exchange.back': 'Назад',
    'exchange.search': 'По��ск',
    'exchange.top_up': 'Пополн��ть',
    'exchange.enter_amount': 'Введите сумму',
    'exchange.select_asset': 'Выберите актив',
    
    // Common
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.continue': 'Продолжить',
    'common.cancel': 'Отмена',
    'common.confirm': 'Подтвердить',
    'common.close': 'Закрыть',
    'common.save': 'Сохранить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.loading': 'Загрузка...',
    'common.error': '����ибка',
    'common.success': 'Ус����шно',
    'common.amount': 'Сумма',
    'common.address': 'Адрес',
    'common.fee': 'Комиссия',
    'common.total': 'Итого',
    'common.available': 'Доступно',
    'common.balance': 'Баланс',
    'common.price': 'Цена',
    'common.volume': 'Объём',
    'common.change': 'Изменение',
    'common.date': 'Дата',
    'common.time': 'Время',
    'common.status': 'Статус',
    'common.type': 'Тип',
    'common.search': 'Поиск',
    'common.back': 'Назад',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортиро��ка',
    'common.all': 'Все',
    'common.none': 'Нет',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.refresh': 'Обновить',
    'common.retry': 'Повторить',
    'common.skip': 'Пропустить',
    'common.done': 'Готов��',
    'common.copied': 'Скопировано',
    'common.copy': 'Копироват��',
    'common.share': 'Поделиться',
    'common.help': 'Помощь',
    'common.support': 'Поддержка',
    'common.about': 'О приложении',
    'common.version': 'Версия',
    'common.update': 'Обновить',
    'common.new': 'Новый',
    'common.old': 'Старый',
    'common.recent': 'Недавн��е',
    'common.popular': 'Популярные',
    'common.recommended': 'Рекомендуемые',
    'common.trending': 'В тренде',
    'common.top': 'Топ',
    'common.bottom': 'Ни��',
    'common.left': 'Слева',
    'common.right': 'Справа',
    'common.center': 'Центр',
    'common.up': 'Вверх',
    'common.down': 'Вниз',
    'common.high': 'Высокий',
    'common.low': 'Низкий',
    'common.medium': 'Средний',
    'common.fast': 'Быстро',
    'common.slow': 'Медленно',
    'common.normal': 'Об��чно',
    'common.custom': 'Наст��оить',
    'common.auto': 'Автоматически',
    'common.manual': 'Вручную',
    'common.optional': 'Опциональн��',
    'common.required': 'Обязательно',
    'common.recommended': '��екомендуется',
  },
  en: {
    // Bottom Navigation
    'nav.wallet': 'Portfolio',
    'nav.market': 'Market',
    'nav.bonuses': 'Bonuses',
    'nav.history': 'History',
    
    // Settings
    'settings.title': 'MAIN SETTINGS',
    'settings.notifications': 'Notifications',
    'settings.passcode': 'Passcode and Face ID',
    'settings.language': 'Language',
    'settings.currency': 'Primary currency',
    'settings.enabled': 'On',
    'settings.verification': 'Verification level',
    'settings.max': 'Max',
    'settings.not_applies': 'Does not apply to CFD Space account.',
    'settings.support': 'Contact support',
    'settings.faq': 'Wallet FAQ',
    'settings.news': 'Wallet News',
    'settings.agreement': 'User agreement',
    'settings.privacy': 'Privacy policy',
    'settings.footer_text': 'Mini-app is managed by TG Wallet Inc.',
    'settings.footer_text2': 'Service is independent and not related to Telegram.',
    'settings.learn_more': 'Learn more',
    'settings.basicSettingsTitle': 'MAIN SETTINGS',
    'settings.walletTab': 'Portfolio',
    'settings.cfdSpaceTab': 'CFD',
    'settings.verificationLevel': 'Verification Level',
    'settings.maxiVerification': 'Max',
    'settings.contactSupport': 'Contact Support',
    'settings.walletFAQ': 'Portfolio FAQ',
    'settings.walletNews': 'Portfolio News',
    'settings.cfdNotApplicable': 'Does apply to CFD account.',
    'settings.userAgreement': 'User Agreement',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.managedBy': 'Mini-app is managed by TG Portfolio Inc.',
    'settings.independent': 'Service is independent and not related to Telegram.',
    'settings.learnMore': 'Learn more',

    // Language Selection
    'language.title': 'LANGUAGE',
    'language.english': 'English',
    'language.russian': 'Russian',
    
    // Notifications
    'notifications.title': 'NOTIFICATIONS',
    'notifications.market_trends': 'Market trends',
    'notifications.market_trends_desc': 'Asset price changes',
    'notifications.updates': 'Updates',
    'notifications.updates_desc': 'New services and features',
    'notifications.promotions': 'Promotions',
    'notifications.promotions_desc': 'Giveaways and bonuses',
    'notifications.educational': 'Educational content',
    'notifications.educational_desc': 'Guides and tips',
    'notifications.feedback': 'Feedback',
    'notifications.feedback_desc': 'Surveys and research',
    'notifications.always_on': 'Transaction and security notifications are always enabled.',
    'notifications.news_channel': 'You can read all news in the channel',
    'notifications.crypto_news': 'Crypto Wallet News',
    'notifications.cfd_title': 'CFD WALLET NOTIFICATIONS',
    'notifications.cfd_for': 'Notifications for',
    'notifications.cfd_desc': 'Get notifications when you receive CFD tokens and NFTs in CFD Wallet.',
    'notifications.cfd_news': 'CFD Wallet News',
    'notifications.cfd_news_text': 'All news can be found in the channel',
    'notifications.on': 'On',
    'notifications.off': 'Off',
    'notifications.enabled': 'On',
    'notifications.disabled': 'Off',
    'notifications.security_notice': 'Transaction and security notifications will always be enabled.',
    'notifications.news_text': 'You can read all news in the channel',
    'notifications.news_channel_link': 'Crypto Wallet News',
    'notifications.cfd_title': 'CFD WALLET NOTIFICATIONS',
    'notifications.cfd_for': 'Notifications for',
    'notifications.cfd_description': 'Get notifications when you receive CFD tokens and NFTs in CFD Wallet.',
    'notifications.cfd_news_text': 'All news can be found in the channel',
    'notifications.cfd_news_channel_link': 'CFD Wallet News',
    
    // Notification Categories
    'notifications.category.market_trends': 'MARKET TRENDS NOTIFICATIONS',
    'notifications.category.updates': 'UPDATE NOTIFICATIONS',
    'notifications.category.promotions': 'PROMOTION NOTIFICATIONS',
    'notifications.category.educational': 'EDUCATIONAL CONTENT NOTIFICATIONS',
    'notifications.category.feedback': 'FEEDBACK NOTIFICATIONS',
    'notifications.category.feedback_desc': 'User surveys that help improve the service.',
    
    // Wallet
    'wallet.title': 'Portfolio',
    'wallet.balance.portfolio': 'Portfolio Balance',
    'wallet.balance.allTime': 'all time',
    'wallet.actions.withdraw': 'Withdraw',
    'wallet.actions.deposit': 'Deposit',
    'wallet.actions.exchange': 'Exchange',
    'wallet.actions.transfer': 'Transfer',
    'wallet.notification.earnTitle': 'Earn up to 15% APY',
    'wallet.notification.withDollars': 'with Nobel Portfolio',
    'wallet.notification.startEarning': 'Start earning →',
    'wallet.assets.title': 'ASSETS',
    'wallet.assets.hide': 'Hide',
    'wallet.assets.show': 'Show',
    'wallet.assets.cashDollars': 'Dollars',
    'wallet.assets.forTrading': 'For trading',
    'wallet.assets.boughtAt': 'Bought for:',
    'wallet.assets.noAssets': 'No assets yet',
    'wallet.assets.buyOnMarket': 'Buy assets on Market page',
    'wallet.trending.title': 'TRENDING',
    'wallet.trending.viewAll': 'All',
    'wallet.trending.perDay': 'per day',
    'wallet.demo.message': '🎭 Demo mode - for full features launch via Telegram bot',
    'wallet.tabs.wallet': 'Portfolio',
    'wallet.tabs.cfd': 'CFD',
    'wallet.settings.open': 'Open settings',
    'wallet.trading.title': 'Trading',
    'wallet.trading.currentPrice': 'Current price',
    'wallet.trading.buy': 'BUY',
    'wallet.trading.sell': 'SELL',
    'wallet.trading.warning': 'Cryptocurrency trading involves high risks',
    'wallet.gold': 'Gold',

    // Додаткові переклади для всіх текстів (англійська)
    'wallet.notification.earnTitle': 'Earn up to 15% APY',
    'wallet.notification.withDollars': 'with Nobel Portfolio',
    'wallet.notification.startEarning': 'Start earning →',
    'wallet.trending.perDay': 'per day',
    'wallet.demo.message': '🎭 Demo mode - for full features launch via Telegram bot',
    'wallet.settings.open': 'Open settings',
    'wallet.assets.boughtFor': 'Bought for',
    'wallet.trends.perDay': 'per day',
    'wallet.assets.dollars_cash': 'Dollars USD',
    'wallet.assets.for_trading': 'for investing',
    'wallet.assets.no_assets': 'No assets yet',
    'wallet.assets.buy_on_market': 'Buy assets on Market page',

    // Market
    'market.title': 'Market',
    'market.trending': 'Trending',
    'market.all_assets': 'All assets',
    'market.crypto': 'Crypto',
    'market.stocks': 'Stocks',
    'market.gold': 'Gold',
    'market.price_change': 'Price change',
    'market.search_placeholder': 'Search',
    'market.trending_title': 'TRENDING',
    'market.per_day': 'per day',
    'market.top_of_day': 'TOP OF DAY',
    'market.tab.all': 'All',
    'market.tab.stocks': 'Stocks',
    'market.tab.crypto': 'Crypto',
    'market.tab.gold': 'Gold',
    'market.asset.gold': 'Gold',
    'market.asset.silver': 'Silver',
    'market.asset.platinum': 'Platinum',
    
    // History
    'history.title': 'History',
    'history.all': 'All',
    'history.deposits': 'Deposits',
    'history.withdrawals': 'Withdrawals',
    'history.trades': 'Trades',
    'history.transfers': 'Transfers',
    'history.no_transactions': 'You don\'t have any transactions yet',
    'history.start_trading': 'Start trading to see history here',
    
    // Bonuses
    'bonuses.title': 'Bonuses',
    'bonuses.available': 'Available bonuses',
    'bonuses.completed': 'Completed',
    'bonuses.no_bonuses': 'You don\'t have any available bonuses yet',
    
    // Asset Details
    'asset.about': 'ABOUT CRYPTOCURRENCY',
    'asset.about_stock': 'ABOUT STOCK',
    'asset.about_gold': 'ABOUT GOLD',
    'asset.about_currency': 'ABOUT CURRENCY',
    'asset.portfolio': 'In portfolio',
    'asset.not_in_portfolio': 'No assets in portfolio',
    'asset.transaction_history': 'Transaction history',
    'asset.no_transactions': 'No transactions with this asset',
    'asset.buy': 'Buy',
    'asset.sell': 'Sell',
    'asset.deposit_btn': 'Deposit',
    'asset.withdraw_btn': 'Withdraw',
    
    // Exchange
    'exchange.title': 'Exchange',
    'exchange.you_pay': 'You pay',
    'exchange.you_receive': 'You receive',
    'exchange.rate': 'Rate',
    'exchange.min_amount': 'Min. amount',
    'exchange.max_amount': 'Max. amount',
    'exchange.exchange_btn': 'Exchange',
    'exchange.insufficient_balance': 'Insufficient balance',
    'exchange.enter_amount': 'Enter amount',
    'exchange.select_asset': 'Select asset',
    
    // Common
    'common.back': 'Back',
    'common.next': 'Next',
    'common.continue': 'Continue',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.amount': 'Amount',
    'common.address': 'Address',
    'common.fee': 'Fee',
    'common.total': 'Total',
    'common.available': 'Available',
    'common.balance': 'Balance',
    'common.price': 'Price',
    'common.volume': 'Volume',
    'common.change': 'Change',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.search': 'Search',
    'common.back': 'Back',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.refresh': 'Refresh',
    'common.retry': 'Retry',
    'common.skip': 'Skip',
    'common.done': 'Done',
    'common.copied': 'Copied',
    'common.copy': 'Copy',
    'common.share': 'Share',
    'common.help': 'Help',
    'common.support': 'Support',
    'common.about': 'About',
    'common.version': 'Version',
    'common.update': 'Update',
    'common.new': 'New',
    'common.old': 'Old',
    'common.recent': 'Recent',
    'common.popular': 'Popular',
    'common.recommended': 'Recommended',
    'common.trending': 'Trending',
    'common.top': 'Top',
    'common.bottom': 'Bottom',
    'common.left': 'Left',
    'common.right': 'Right',
    'common.center': 'Center',
    'common.up': 'Up',
    'common.down': 'Down',
    'common.high': 'High',
    'common.low': 'Low',
    'common.medium': 'Medium',
    'common.fast': 'Fast',
    'common.slow': 'Slow',
    'common.normal': 'Normal',
    'common.custom': 'Custom',
    'common.auto': 'Auto',
    'common.manual': 'Manual',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.recommended': 'Recommended',

    // Deposit Pages (English)
    'deposit.method.title': 'How would you like to buy',
    'deposit.method.subtitle': 'cryptocurrency',
    'deposit.method.bank_card': 'Bank Card',
    'deposit.method.bank_card_desc': 'Buy cryptocurrency by card',
    'deposit.method.p2p_express': 'P2P Express',
    'deposit.method.p2p_express_desc': 'Deals with reliable sellers',
    'deposit.method.p2p_market': 'P2P Market',
    'deposit.method.p2p_market_desc': 'Buy without intermediaries',
    'deposit.method.telegram_stars': 'Top up via Telegram Stars',
    'deposit.method.external_wallet': 'External Wallet',
    'deposit.method.external_wallet_desc': 'Transfer from another wallet',

    // Deposit Asset Selection (English)
    'deposit.asset.popular': 'POPULAR',
    'deposit.asset.all': 'ALL',
    'deposit.asset.not_found': 'Assets not found',

    // Deposit Network Selection (English)
    'deposit.network.warning': 'Make sure you select the correct network. Wrong choice may lead to loss of funds.',
    'deposit.network.select': 'SELECT NETWORK',

    // Deposit Address (English)
    'deposit.address.title': 'Your address in',
    'deposit.address.warning_start': 'Send only',
    'deposit.address.warning_end': 'Assets from other networks or NFTs will be permanently lost.',
    'deposit.address.qr_description': 'Scan QR code to send',
    'deposit.address.qr_description_end': 'to your wallet.',
    'deposit.address.your_address': 'Your address',
    'deposit.address.copy': 'Copy address',
    'deposit.address.copied': 'Address copied to buffer',
    'deposit.address.copied_notification': 'Address copied to buffer.',

    // Withdraw Pages (English)
    'withdraw.method.title': 'How to send',
    'withdraw.method.subtitle': 'cryptocurrency',
    'withdraw.method.telegram.title': 'Telegram Contact',
    'withdraw.method.telegram.description': 'Instant and no fees',
    'withdraw.method.external.title': 'External wallet or exchange',
    'withdraw.method.external.description': 'Need to specify crypto address',

    // Withdraw Asset Selection (English)
    'withdraw.asset.title': 'YOU WITHDRAW',
    'withdraw.asset.dollars': 'Dollars',

    // Withdraw Amount (English)
    'withdraw.amount.insufficient_funds': 'Insufficient funds.',
    'withdraw.amount.buy_more': 'Buy more.',
    'withdraw.amount.balance': 'Balance',
    'withdraw.amount.max': 'Max',
    'withdraw.amount.next': 'Next',

    // Withdraw Processing (English)
    'withdraw.processing.exchange_completed': 'Exchange completed!',
    'withdraw.processing.payment_processing': 'Your payment is processing',
    'withdraw.processing.exchange_success': 'You successfully exchanged {amount} USD for {starsAmount} Telegram Stars',
    'withdraw.processing.stars_available': 'Stars are already available in your Telegram account',
    'withdraw.processing.time_estimate': 'This will take 5 to 20 minutes',
    'withdraw.processing.notification_promise': 'We will notify you when the transaction is confirmed',
    'withdraw.processing.amount': 'Amount',
    'withdraw.processing.received': 'Received',
    'withdraw.processing.recipient': 'Recipient',
    'withdraw.processing.network': 'Network',
    'withdraw.processing.status': 'Status',
    'withdraw.processing.return_to_portfolio': 'Return to portfolio',
    'withdraw.processing.telegram_stars_exchange': 'Telegram Stars exchange',
    'withdraw.processing.external_withdrawal': 'External wallet withdrawal',

    // CFD Page (English)
    'cfd.title': 'CFD Trading',
    'cfd.balance.title': 'CFD Balance',
    'cfd.balance.description': 'Funds for contracts for difference',
    'cfd.trading_balance': 'CFD Trading Balance',
    'cfd.search_assets': 'Search assets',
    'cfd.popular_pairs': 'POPULAR PAIRS',
    'cfd.buy': 'BUY',
    'cfd.sell': 'SELL',
    'cfd.nav.market': 'Market',
    'cfd.nav.trades': 'Trades',
    'cfd.nav.autotrading': 'Auto Trading',
    'cfd.nav.history': 'History',

    // Asset Detail Page (English)
    'asset.name.dollars': 'Dollars',
    'asset.name.toncoin': 'Toncoin',
    'asset.name.bitcoin': 'Bitcoin',
    'asset.name.ethereum': 'Ethereum',
    'asset.name.gold': 'Gold',
    'asset.header.wallet_verified': 'Wallet ✓',
    'asset.header.mini_app': 'mini app',
    'asset.action.send': 'Send',
    'asset.action.receive': 'Receive',
    'asset.action.buy': 'Buy',
    'asset.action.exchange': 'Exchange',
    'asset.price.title': 'PRICE',
    'asset.price.details': 'Details',
    'asset.price.24h': '24h',
    'asset.transaction_history': 'TRANSACTION HISTORY',
    'asset.transaction.exchange_btc_usdt': 'Exchange: BTC to USDT',
    'asset.transaction.exchange_ton_btc': 'Exchange: TON to BTC',
    'asset.transaction.status.sent': 'Sent',
    'asset.transaction.status.received': 'Received',
    'asset.transaction.date.dec_6': '6 Dec 2024 at 1...',
    'asset.transaction.date.nov_16': '16 Nov 2024...',
    'asset.not_found': 'Asset not found',

    // CoinDetail Page (English)
    'coin.about_crypto': 'ABOUT CRYPTOCURRENCY',
    'coin.about_stock': 'ABOUT STOCK',
    'coin.about_precious_metal': 'ABOUT PRECIOUS METAL',
    'coin.about_currency': 'ABOUT CURRENCY',
    'coin.portfolio_section': 'IN PORTFOLIO',
    'coin.read_more': 'Read more',
    'coin.portfolio_empty': 'No assets in portfolio',
    'coin.time_period.1d': '1D',
    'coin.time_period.7d': '7D',
    'coin.time_period.1m': '1M',
    'coin.time_period.1y': '1Y',
    'coin.time_period.all': 'All',
    'coin.today': 'Today',
    'coin.btc_description': 'Bitcoin is the first and most famous cryptocurrency in the world. Created in 2009 by Satoshi Nakamoto as a decentralized digital currency.',
    'coin.btc_point_1': 'You can buy, sell or store BTC in the Wallet.',
    'coin.btc_point_2': 'Bitcoin uses blockchain technology to ensure security and transparency.',
    'coin.eth_description': 'Ethereum is a platform for smart contracts and decentralized applications (DApps), launched in 2015.',
    'coin.eth_point_1': 'You can buy, sell or store ETH in the Wallet.',
    'coin.eth_point_2': 'Ethereum is the foundation for many DeFi projects and NFTs.',
    'coin.aapl_description': 'Apple Inc. is an American multinational technology corporation known for its iPhone, iPad, Mac and other devices.',
    'coin.xrp_description': 'XRP is a digital currency created by Ripple for instant international transfers and payments.',
    'coin.xrp_point_1': 'You can buy, sell or store XRP in the Wallet.',
    'coin.xrp_point_2': 'XRP is used by banks and financial institutions for fast transfers.',
    'coin.generic_crypto_description': '{{name}} is a cryptocurrency based on blockchain technology. Allows fast and secure digital transactions.',
    'coin.generic_crypto_point_1': 'You can buy, sell or store {{symbol}} in the Wallet.',
    'coin.generic_crypto_point_2': 'Cryptocurrencies can have high price volatility.',
    'coin.gold_description': 'Gold is a precious metal that has been used for millennia as a store of value and protection against inflation.',
    'coin.gold_point_1': 'You can buy or sell gold through the platform.',
    'coin.gold_point_2': 'Gold is traditionally considered a "safe haven" for investors.',

    // History (English)
    'history.subtitle': 'All your transactions and operations',
    'history.filter.all': 'All',
    'history.filter.buy': 'Purchases',
    'history.filter.sell': 'Sales',
    'history.filter.deposit': 'Deposits',
    'history.filter.withdraw': 'Withdrawals',
    'history.empty.title': 'No transactions yet',
    'history.empty.subtitle_all': 'Your operations will appear here',
    'history.empty.subtitle_filtered': 'No operations of this type',
    'history.empty.go_to_market': 'Go to trading',
    'history.transaction.buy': 'Purchase',
    'history.transaction.sell': 'Sale',
    'history.transaction.asset': 'asset',
    'history.transaction.deposit': 'Deposit with stars',
    'history.transaction.withdraw': 'Withdraw to stars',
    'history.transaction.transfer_to_cfd': 'Transfer to CFD',
    'history.transaction.transfer_from_cfd': 'Transfer from CFD',
    'history.transaction.default': 'Transaction',
    'history.time.now': 'Just now',
    'history.time.hours_ago': 'h ago',
    'history.time.days_ago': 'd ago',
    'history.portfolio.total_value': 'Total portfolio value',
    'history.portfolio.cash': 'Cash',
    'history.status.completed': 'Completed',
    'history.status.pending': 'Pending',
    'history.status.processing': 'Processing',
    'history.status.failed': 'Failed',

    // History Details Modal
    'history.details.title': 'Transaction Details',
    'history.details.group.label': 'Operation Type',
    'history.details.group.purchase': 'Purchase',
    'history.details.group.sale': 'Sale',
    'history.details.group.deposit': 'Deposit',
    'history.details.group.withdrawal': 'Withdrawal',
    'history.details.group.transfer': 'Transfer',
    'history.details.group.other': 'Other',
    'history.details.id': 'Transaction ID',
    'history.details.amount': 'Amount',
    'history.details.instrument': 'Instrument',
    'history.details.exchange_rate': 'Exchange Rate',
    'history.details.purchase_price': 'Purchase Price',
    'history.details.quantity': 'Quantity',
    'history.details.time': 'Time',
    'history.details.status': 'Status',
    'history.details.description': 'Description',

    // Bonuses (English)
    'bonuses.hero.title': 'Wallet Bonuses',
    'bonuses.hero.subtitle': 'Get bonuses for storing cryptocurrency.',
    'bonuses.hero.how_it_works': 'How it works',
    'bonuses.tabs.active': 'Active',
    'bonuses.tabs.completed': 'Completed',
    'bonuses.card.bonus_label': 'BONUS',
    'bonuses.card.annual': 'annually',
    'bonuses.empty.completed': 'No completed bonuses',
    'bonuses.asset.dollars': 'Dollars',

    // Exchange (English)
    'exchange.title': 'Exchange',
    'exchange.you_pay': 'You pay',
    'exchange.you_receive': 'You receive',
    'exchange.max': 'Max',
    'exchange.asset.dollars': 'Dollars',
    'exchange.top_up': 'Top up',
    'exchange.insufficient_funds': 'Insufficient funds.',
    'exchange.select_instrument': 'Select instrument',
    'exchange.exchanging': 'Exchanging...',
    'exchange.review_deal': 'Review deal',
    'exchange.error.exchange_failed': 'Error during asset exchange',
    'exchange.max': 'Max',
    'exchange.processing': 'Exchanging...',
    'exchange.back': 'Back',
    'exchange.search': 'Search',
    'exchange.top_up': 'Top up',

    // Transfer (English)
    'transfer.title': 'Transfer funds',
    'transfer.subtitle': 'Between Portfolio and CFD',
    'transfer.portfolio': 'Portfolio',
    'transfer.cash': 'Cash',
    'transfer.for_trading': 'For trading',
    'transfer.direction.to_cfd': 'Transfer to CFD',
    'transfer.direction.from_cfd': 'Transfer from CFD',
    'transfer.amount_label': 'Transfer amount',
    'transfer.all_amount': 'All amount',
    'transfer.available': 'Available',
    'transfer.amount': 'Amount',
    'transfer.from': 'From',
    'transfer.to': 'To',
    'transfer.fee': 'Fee',
    'transfer.transferring': 'Transferring...',
    'transfer.transfer_button': 'Transfer',
    'transfer.info.title': 'About transfer',
    'transfer.info.portfolio_desc': 'Portfolio - cash for buying assets',
    'transfer.info.cfd_desc': 'CFD - funds for contracts for difference',
    'transfer.info.instant_free': 'Transfer is instant and free',
    'transfer.info.history_saved': 'All operations are saved in history',
    'transfer.error.invalid_amount': 'Invalid amount',
    'transfer.error.insufficient_funds': 'Insufficient funds',
    'transfer.error.transfer_failed': 'Transfer error',
  },
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'ru';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
